version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000
        depends_on: 
            - db

    queue:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306